### ISSUE TITLE
SM2加密后用后端不能100%解密

### ISSUE THREAD

**Issue by hwenb** [44021987/smEncrypt#2]
后端我是用的bouncycastle解密，解密前要在加密后的字符串前面加上04，不是每个密钥解密都可以解开，

**Comment by 44021987** [comment]
> 后端我是用的bouncycastle解密，解密前要在加密后的字符串前面加上04，不是每个密钥解密都可以解开，

有2种方式，一种加密后密文会加上04，一种不加，要根据你的需求来。
